# Generated by Django 4.2.23 on 2025-07-20 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_alter_group_group_name'),
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupEval',
            fields=[
                ('evaluation_id', models.AutoField(primary_key=True, serialize=False)),
                ('week_start_date', models.DateTimeField()),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('evaluator_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_evals', to=settings.AUTH_USER_MODEL)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('target_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_evals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_status', models.IntegerField(choices=[(0, '대기'), (1, '승인'), (2, '반려')], default=0)),
                ('review_at', models.DateTimeField(blank=True, null=True)),
                ('good_count', models.IntegerField()),
                ('bad_count', models.IntegerField()),
                ('checklist_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklists.checklistitem')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
