# Generated by Django 4.2.23 on 2025-07-07 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
        ("users", "0003_alter_user_clean_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="groups.group",
            ),
        ),
    ]
