# Generated by Django 4.2.23 on 2025-07-11 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_alter_group_group_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('space_id', models.AutoField(primary_key=True, serialize=False)),
                ('space_name', models.CharField(max_length=255)),
                ('space_type', models.IntegerField(choices=[(0, '공용 공간'), (1, '개인 공간')])),
                ('start_x', models.IntegerField()),
                ('start_y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('size', models.IntegerField()),
                ('direction', models.IntegerField(choices=[(0, '가로'), (1, '세로')])),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='groups.group')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('start_x', models.IntegerField()),
                ('start_y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('size', models.IntegerField()),
                ('parent_space', models.ForeignKey(db_column='parent_space_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='spaces.space')),
            ],
        ),
    ]
