# Generated by Django 4.2.23 on 2025-07-16 00:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='direction',
            field=models.CharField(choices=[('horizontal', '가로'), ('vertical', '세로')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='height',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.IntegerField(choices=[(1, '1배'), (2, '2배')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_x',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_y',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='width',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='space',
            name='direction',
            field=models.CharField(choices=[('horizontal', '가로'), ('vertical', '세로')], max_length=10),
        ),
        migrations.AlterField(
            model_name='space',
            name='height',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='space',
            name='size',
            field=models.IntegerField(choices=[(1, '1배'), (2, '2배')]),
        ),
        migrations.AlterField(
            model_name='space',
            name='space_type',
            field=models.IntegerField(choices=[(0, 'Public'), (1, 'Private')]),
        ),
        migrations.AlterField(
            model_name='space',
            name='start_x',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='space',
            name='start_y',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='space',
            name='width',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
