# Generated by Django 4.2.23 on 2025-07-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("group_id", models.AutoField(primary_key=True, serialize=False)),
                ("group_name", models.CharField()),
                ("group_rule", models.TextField(blank=True, null=True)),
                ("group_created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
