# Generated by Django 4.2.23 on 2025-07-20 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spaces', '0002_item_direction_alter_item_height_alter_item_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('checklist_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_count', models.IntegerField(null=True)),
                ('completed_count', models.IntegerField(null=True)),
                ('space_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.space')),
            ],
        ),
        migrations.CreateModel(
            name='Checklistitem',
            fields=[
                ('checklist_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('due_date', models.DateTimeField()),
                ('complete_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, '미완료'), (1, '기한 내 완료'), (2, '마감 기한 지남')], default=0)),
                ('unit_item', models.CharField(max_length=255)),
                ('checklist_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='checklists.checklist')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
