# Generated by Django 4.2.23 on 2025-07-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='unit_item',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
