# Generated by Django 4.2.23 on 2025-07-12 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='space_parent_id',
        ),
        migrations.AlterField(
            model_name='checklist',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.item'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Space',
        ),
    ]
